version: '2'
services:
    api:
        mem_limit: 2g
        image: "215519188259.dkr.ecr.ap-southeast-1.amazonaws.com/digimed/evermind-backend:nightly"
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
            ElasticSearch__Host: "http://elasticsearch"
            ElasticSearch__Port: "9200"
            Storage__ServerUrl: "http://storage_api/"
            Storage__PublicUrl: "https://nightly-evermind.antoan.org/storage/"
            FilePreview__ServerUrl: "http://preview_api/"
            FilePreview__PublicUrl: "https://nightly-evermind.antoan.org/preview/"
            PublicUrl: "https://nightly-evermind.antoan.org/"
            db_host: "api_database"
            db_port: "5432"
            db_username: "postgres"
            db_password: "DigiMed123"
            db_name: "evermind"
        build:
            context: ./evermind-backend
        ports:
            - "9001:80"
        links:
            - elasticsearch
            - api_database
            - storage_api
            - preview_api
        # alter docker command to wait for postgres to start
        working_dir: /app
        command: "./wait_for_it.sh api_database:5432 -- ./docker_run.sh"
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "api"

    api_database:
        image: "postgres:9.4"
        ports:
            - "9002:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind"
        volumes:
            - api_database_reset:/var/lib/postgresql/data
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "api_database"

    elasticsearch:
        image: "mahpah/elasticsearch-icu:5.5.1"
        ports:
            - "9003:9200"
        environment:
            http.host: "0.0.0.0"
            transport.host: "127.0.0.1"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"

        volumes:
            - esdata:/usr/share/elasticsearch/data
        mem_limit: 1g
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "elasticsearch"

    media_api:
        image: "215519188259.dkr.ecr.ap-southeast-1.amazonaws.com/digimed/evermind-media:nightly"
        build:
            context: ./evermind-media
        environment:
            NODE_ENV: "docker"
            DEBUG: "*"
            MEDIA_ROOT_URI: 'https://nightly-evermind.antoan.org/media/'
        ports:
          - "9004:7777"
        links:
          - media_database
        volumes:
          - media_tmp:/var/tmp
          - media:/var/www/media

        # alter docker command to wait for postgres to start
        working_dir: /evermind-media
        command: "/bin/bash /evermind-media/scripts/wait_for_it.sh pg:5432 -- node dist/index.js"

        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "media_api"

    media_database:
        mem_limit: 128m
        image: "postgres:9.4"
        ports:
          - "9005:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind-media"
        volumes:
            - media_database:/var/lib/postgresql/data
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "media_database"

    storage_api:
        image: "215519188259.dkr.ecr.ap-southeast-1.amazonaws.com/digimed/evermind-storage:nightly"
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
            db_host: "storage_database"
            db_port: "5432"
            db_username: "postgres"
            db_password: "DigiMed123"
            db_name: "evermind-storage"
        build:
            context: ./evermind-storage
        ports:
            - "9006:80"
        links:
            - storage_database
        volumes:
            - evm-storage:/evm-storage

        # alter docker command to wait for postgres to start
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "storage_api"

    storage_database:
        mem_limit: 128m
        image: "postgres:9.4"
        ports:
            - "9007:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind-storage"
        volumes:
            - storage_database:/var/lib/postgresql/data
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "storage_database"

    preview_api:
        mem_limit: 2g
        image: "215519188259.dkr.ecr.ap-southeast-1.amazonaws.com/digimed/evermind-preview:nightly"
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
            FileProcessor__MediaServerUrl: "https://nightly-evermind.antoan.org/media/"
            PublicUrl: "https://nightly-evermind.antoan.org/preview/"
            db_host: "preview_database"
            db_port: "5432"
            db_username: "postgres"
            db_password: "DigiMed123"
            db_name: "evermind-preview"
        build:
            context: ./evermind-preview
        ports:
          - "9008:80"
        links:
          - preview_database
          - media_api
        volumes:
          - preview-storage:/data

        # alter docker command to wait for postgres to start
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "preview_api"

    preview_database:
        mem_limit: 128m
        image: "postgres:9.4"
        ports:
          - "9009:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind-preview"
        volumes:
            - preview_pgdata:/var/lib/postgresql/data
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "preview_database"

    frontend:
        mem_limit: 128m
        image: "215519188259.dkr.ecr.ap-southeast-1.amazonaws.com/digimed/evermind-frontend:nightly"
        build:
            context: ./evermind-frontend
        ports:
            - "80:80"
        links:
            - api
            - preview_api
            - storage_api
            - media_api
        working_dir: /app
        command: "./wait_for_it.sh api:80 -- ./wait_for_it.sh storage_api:80 -- ./wait_for_it.sh preview_api:80 -- ./wait_for_it.sh media_api:80 -- nginx -g 'daemon off;'"
        logging:
            driver: awslogs
            options:
                awslogs-group: "evermind-nightly"
                awslogs-region: "ap-southeast-1"
                awslogs-stream-prefix: "frontend"
