version: '3'
services:
    api:
        image: digimed/evermind-backend:nightly
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
            ConnectionStrings__DefaultConnection: "User ID=postgres;Password=DigiMed123;Host=api_database;Port=5432;Database=evermind;Pooling=true;"
            ElasticSearch__Host: "http://elasticsearch"
            ElasticSearch__Port: "9200"
            Storage__FileServerUrl: "http://storage_api"
            FilePreview__FileServerUrl: "http://preview_api"
        build:
            context: ./evermind-backend
            dockerfile: Dockerfile.nightly
        ports:
            - "9001:80"
        depends_on:
            - elasticsearch
            - api_database
        # alter docker command to wait for postgres to start
        working_dir: /app
        command: "./wait_for_it.sh api_database:5432 -- ./docker_run.sh api_database 5432 evermind postgres DigiMed123 elasticsearch:9200"

    api_database:
        image: "postgres"
        ports:
            - "9002:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind"
        volumes:
            - ./volumes/api_database:/var/lib/postgresql/data

    elasticsearch:
        image: "mahpah/elasticsearch-icu:5.5.1"
        ports:
            - "9003:9200"
        environment:
            http.host: "0.0.0.0"
            transport.host: "127.0.0.1"
        volumes:
            - ./volumes/esdata:/usr/share/elasticsearch/data

    media_api:
        environment:
            NODE_ENV: "docker"
            DEBUG: "*"
        build:
            context: ./evermind-media
        ports:
          - "9004:7777"
        depends_on:
          - media_database
        volumes:
          - ./volumes/tmp:/var/tmp
          - ./volumes/media:/var/www/media

        # alter docker command to wait for postgres to start
        working_dir: /evermind-media
        command: "/bin/bash /evermind-media/scripts/wait_for_it.sh pg:5432 -- node dist/index.js"

    media_database:
        image: "postgres"
        ports:
          - "9005:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind-media"
        volumes:
            - ./volumes/media_database:/var/lib/postgresql/data

    storage_api:
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
            ConnectionStrings__DefaultConnection: "User ID=postgres;Password=DigiMed123;Host=storage_database;Port=5432;Database=evermind-storage;Pooling=true;"
        build:
            context: ./evermind-storage
        ports:
            - "9006:80"
        depends_on:
            - storage_database
        volumes:
            - ./volumes/evm-storage:/evm-storage

        # alter docker command to wait for postgres to start
        working_dir: /app
        command: "/bin/bash /app/scripts/wait_for_it.sh storage_database:5432 -- dotnet EVM.StorageApi.dll"

    storage_database:
        image: "postgres"
        ports:
            - "9007:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind-storage"
        volumes:
            - ./volumes/storage_database:/var/lib/postgresql/data

    preview_api:
        environment:
          ASPNETCORE_ENVIRONMENT: "Docker"
          ConnectionStrings__DefaultConnection: "User ID=postgres;Password=DigiMed123;Host=preview_database;Port=5432;Database=evermind;Pooling=true;"
        build:
            context: ./evermind-generate-document-preview
        ports:
          - "9008:80"
        depends_on:
          - preview_database
        volumes:
          - ./volumes/preview-storage:/preview-storage

        # alter docker command to wait for postgres to start
        working_dir: /app
        command: "/bin/bash /app/scripts/wait_for_it.sh preview_database:5432 -- dotnet Evermind.FilePreviewApi.dll"

    preview_database:
        image: "postgres"
        ports:
          - "9009:5432"
        environment:
            POSTGRES_PASSWORD: "DigiMed123"
            POSTGRES_DB: "evermind_files_preview"
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data

    frontend:
        image: evermind-frontend:nightly
        build:
            context: ./evermind-frontend
        ports:
          - "9010:80"
        working_dir: /app
        command: "/app/wait_for_it.sh api:80 -- nginx -g 'daemon off;'"

